homeassistant:
  # Name of the location where Home Assistant is running
  name: PanterHome
  # Location required to calculate the time the sun rises and sets
  latitude: 51.826632
  longitude: 5.843140
  elevation: 30
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize:
    scene.all_off:
      icon: mdi:candle
      friendly_name: "All lights off"
    sensor.light_lux_sensor_2_0:
      friendly_name: "Light Sensor"
    light.hue_lamp_2:
      friendly_name: "sta lamp 2"
    light.hue_lamp_3:
      friendly_name: "sta lamp 1"
    input_boolean.away:
      icon: mdi:home
    scene.table_full_on:
      icon: mdi:brightness-5
    scene.table_on:
      icon: mdi:brightness-6
    script.living_default_on:
      icon: mdi:brightness-6

    
# Discover some devices automatically
# discovery:

http:
  api_password: !secret http_password 

light:
  platform: hue
  host: 192.168.2.1

recorder:
  purge_days: 4

updater:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Allows you to issue voice commands from the frontend
# conversation:

# Track the sun
sun:

# View all events in a logbook
logbook:

config:

mysensors: !include configs/mysensors.yaml

scene powerview:
  platform: hunterdouglas_powerview
  address: 192.168.2.4

input_boolean:
  away:
    name: Away
    initial: off

shell_command:
  update_restart: bash /home/pi/.homeassistant/update_restart.sh

scene: !include configs/scenes.yaml

script:
  lights_on_sunset:
    alias: Turn lights on if sun has set
    sequence:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - service: script.turn_on
        entity_id: 
        - script.living_default_on
        - script.bar_on
  blind_scene_at_time:
    alias: Activate a blind scene depending on time.
    sequence:
      - condition: time
        after: '7:00:00'
        before: '8:00:00'
      - service: scene.turn_on
        entity_id: scene.7247  #blinds semi close
  update_restart:
    sequence:
      - service: shell_command.update_restart
  wandlamp_on:
    sequence:
      - service: light.turn_on
        entity_id: light.wandlamp1
        data:
          brightness: 85
          xy_color: [0.5268,0.4133]
      - service: light.turn_on
        entity_id: light.wandlamp2
        data:
          brightness: 85
          xy_color: [0.5268,0.4133]
  tv_lamp_on:
    sequence:
      - service: light.turn_on
        entity_id: light.tv_lamp
        data:
          xy_color: [0.5144,0.4148]
          brightness: 25
  sta_lamp_on:
    sequence:
      - service: light.turn_on
        entity_id: light.hue_lamp_2
        data:
          xy_color: [0.5134,0.4149]
          brightness: 97
      - service: light.turn_on
        entity_id: light.hue_lamp_3
        data:
          xy_color: [0.5134,0.4149]
          brightness: 71
  bar_on:
    sequence:
    - service: light.turn_on
      entity_id: light.bar_lamp
      data:
        xy_color: [0.5134,0.4149]
        brightness: 150
  living_default_on:
    alias: Easy lighting.
    sequence:
      - service: script.turn_on
        entity_id: 
        - script.wandlamp_on
        - script.tv_lamp_on
        - script.sta_lamp_on
        

automation: !include configs/automation.yaml

notify:
  platform: telegram
  api_key: !secret telegram_api_key
  chat_id: !secret telegram_chat_id

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_host
    username: !secret ddwrt_user_name
    password: !secret ddwrt_password
    consider_home: 120
    interval_seconds: 20

# hass_telepot:
#     bot_token: !secret telepot_api_key
#     allowed_chat_ids: !secret telepot_chat_id
#     commands:
#     -   command: away
#         script:
#             service: input_boolean.turn_on
#             entity_id: input_boolean.away
#     -   command: athome
#         script:
#             service: input_boolean.turn_off
#             entity_id: input_boolean.away
#     -   command: presence
#         response:
#             text: Please choose whether you are at home or not
#             keyboard:
#             -   away
#             -   athome
#     -   command: alloff
#         script:
#             service: scene.turn_on
#             entity_id: scene.all_off



group: !include configs/groups.yaml

climate: !include configs/honeywell.yaml

sensor:
  - platform: template
    sensors:
      main_button:
        icon_template: mdi:battery-90
        friendly_name: 'Main button'
        value_template: '{{ states.sensor.scene_controller_1_10.attributes.battery_level}}'
        unit_of_measurement: '%'
      light_sensor:
        icon_template: mdi:battery-90
        friendly_name: 'Light sensor'
        value_template: '{{ states.sensor.light_lux_sensor_2_0.attributes.battery_level}}'
        unit_of_measurement: '%'