homeassistant:
  # Name of the location where Home Assistant is running
  name: PanterHome
  # Location required to calculate the time the sun rises and sets
  latitude: 51.826632
  longitude: 5.843140
  elevation: 30
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  customize:
    script.all_off:
      icon: mdi:candle
    sensor.light_lux_sensor_2_0:
      friendly_name: "Light Sensor"
    light.hue_lamp_2:
      friendly_name: "sta lamp 2"
    light.hue_lamp_3:
      friendly_name: "sta lamp 1"
    input_boolean.away:
      icon: mdi:home
    scene.table_full_on:
      icon: mdi:brightness-5
    scene.table_on:
      icon: mdi:brightness-6
    script.living_default_on:
      icon: mdi:brightness-6

logger:
  default: warn
  logs:
    custom_components.homematic_ip: error
    homematicip: error
    
# media_player:
#   - platform: cast
#     host: '192.168.2.6'

http:
  api_password: !secret http_password 

light:
  platform: hue
  host: 192.168.2.1

recorder:
  purge_keep_days: 3
  purge_interval: 2
  exclude:
    entities:
      - sensor.light_lux_sensor_2_0
      - sensor.light_sensor
      - sun.sun
  #  - sensor.light_lux_sensor_2_0

# hass_aggregator:
#   - entity_id: sensor.light_lux_sensor_2_0
#     aggregator:
#       method: min
#       range: 10
#   - entity_id: sensor.light_lux_sensor_2_0
#     aggregator:
#       method: maxevery
#       cycle: 20 # minutees

updater:

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Allows you to issue voice commands from the frontend
# conversation:

# Track the sun
sun:

config:

mysensors: !include configs/mysensors.yaml

scene powerview:
  platform: hunterdouglas_powerview
  address: 192.168.2.4

input_boolean:
  away:
    name: Away
    initial: off

shell_command:
  update_restart: bash /home/pi/.homeassistant/update_restart.sh

scene: !include configs/scenes.yaml

script: !include scripts.yaml


automation: !include automations.yaml

telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids: !secret telepot_chat_id

notify:
  platform: telegram
  chat_id: !secret telegram_chat_id


# homematic_ip:
#   authtoken: !secret hmip_auth_token
#   accesspoint: !secret hmip_auth_access_point

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_host
    username: !secret ddwrt_user_name
    password: !secret ddwrt_password
    consider_home: 120
    interval_seconds: 20

group: !include configs/groups.yaml

climate: !include configs/honeywell.yaml

sensor:
  - platform: template
    sensors:
      main_button:
        icon_template: mdi:battery-90
        friendly_name: 'Main button'
        value_template: '{{ states.sensor.scene_controller_1_10.attributes.battery_level}}'
        unit_of_measurement: '%'
      light_sensor:
        icon_template: mdi:battery-90
        friendly_name: 'Light sensor'
        value_template: '{{ states.sensor.light_lux_sensor_2_0.attributes.battery_level}}'
        unit_of_measurement: '%'