- alias: Set hoeklamp when triggered on
  trigger:
    platform: state
    entity_id: light.hoeklamp
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.hoeklamp_on
# - alias: switch off lights when lux > 800
#   trigger:
#     platform: numeric_state
#     entity_id: sensor.light_lux_sensor_2_0
#     value_template: '{{ state.attributes.V_LEVEL }}'
#     above: 800
#   condition:
#     condition: or
#     conditions:
#       - condition: state
#         entity_id: group.living
#         state: 'on'
#       - condition: state
#         entity_id: group.dining
#         state: 'on'
#       - condition: state
#         entity_id: group.bar
#         state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id:
#         - group.living
#         - group.dining
#         - group.bar
#     - service: notify.notify
#       data:
#         message: lux levels above 800. Switching lights off downstairs.
- alias: scene controller tap hold action
  trigger:
    platform: state
    entity_id: sensor.scene_controller_1_10
    to: "3"
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
- alias: scene controller single tap action
  trigger:
    platform: state
    entity_id: sensor.scene_controller_1_10
    to: "1"
  action:
    - service: scene.turn_on
      entity_id:
        - scene.table_on
        - scene.living_on
    - service: script.turn_on
      entity_id: 
        - script.lights_on_sunset
        - script.blind_scene_at_time
        #- script.blind_scene_at_time_and_sunrise
- alias: scene controller double tap option
  trigger:
    platform: state
    entity_id: sensor.scene_controller_1_10
    to: "2"
  action:
    - service: scene.turn_on
      entity_id:
        - scene.table_full_on
- alias: lights on at sunset if living lights are on
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.dining
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: 
      - scene.bar_on
      - scene.hoeklamp_on
      - scene.tv_light_on
- alias: bar light off at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id:
        - group.bar
        - light.hoeklamp
        - light.tv_lamp
- alias: notify if light switches on or off depending on away state.
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: light
  condition:
    condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
    - delay: 00:00:02
    - service: notify.notify
      data:
        message: A light is switched on or off
- alias: notify when away mode changes.
  trigger:
    platform: state
    entity_id: input_boolean.away
  action:
    service: notify.notify
    data_template:
      message: >
        Away mode changed to {{ trigger.to_state.state }}
- alias: notify when sander leaves.
  trigger:
    platform: state
    entity_id: device_tracker.c0eefbd3c35f
    from: 'home'
    to: 'not_home'
  action:
    service: notify.notify
    data:
      message: Sander has left.
- alias: activate blind at sunrise but after 8
  trigger:
    - platform: sun
      event: sunrise
    - platform: time
      after: '8:00:00'
  condition:
    condition: time
    after: '8:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.64040
- alias: put the shade in privacy mode at a certain time
  trigger:
    - platform: time
      after: '19:00:00'
    - platform: sun
      event: sunset
  condition:
    condition: sun
    before: sunset
    before_offset: '1:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.7247
- alias: Put the shade in night mode when completely dark
  trigger:
    - platform: sun
      event: sunset
      offset: '1:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.60133