#######################################################
# Scene controller triggers
#######################################################    
- alias: scene controller tap hold action
  trigger:
    platform: state
    entity_id: sensor.scene_controller_1_10
    to: "3"
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
- alias: scene controller single tap action
  trigger:
    platform: state
    entity_id: sensor.scene_controller_1_10
    to: "1"
  action:
    - service: scene.turn_on
      entity_id:
        - scene.table_on
        #- scene.living_on
    - service: script.turn_on
      entity_id: 
        - script.lights_on_sunset
        - script.blind_scene_at_time
- alias: scene controller double tap option
  trigger:
    platform: state
    entity_id: sensor.scene_controller_1_10
    to: "2"
  action:
    - service: scene.turn_on
      entity_id:
        - scene.table_full_on
#######################################################
# Light automations
#######################################################            
- alias: lights on at sunset if living lights are on
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.dining
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: 
      - script.living_default_on
      - script.bar_on
- alias: all lights except table lights off at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id:
        - group.bar
        - group.living
# - alias: Set stalamp when triggered on
#   trigger:
#     platform: state
#     entity_id: light.hoeklamp
#     from: 'off'
#     to: 'on'
#   action:
#     service: scene.turn_on
#     entity_id: scene.hoeklamp_on
#######################################################
# Notifications
#######################################################    
- alias: notify if light switches on or off depending on away state.
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: light
  condition:
    condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
    - delay: 00:00:02
    - service: notify.notify
      data:
        message: A light is switched on or off
- alias: notify when away mode changes.
  trigger:
    platform: state
    entity_id: input_boolean.away
  action:
    service: notify.notify
    data:
      message: 'Away mode changed /awayon .'
      # data:
      #   inline_keyboard:
      #     - 'Away on:/awayon'
      #     - 'Away off:/awayoff'
    # data_template:
    #   message: >
    #     Away mode changed to {{ trigger.to_state.state }}
# - alias: notify when sander leaves.
#   trigger:
#     platform: state
#     entity_id: device_tracker.c0eefbd3c35f
#     from: 'home'
#     to: 'not_home'
#   action:
#     service: notify.notify
#     data:
#       message: Sander has left.
- alias: notify when all have left.
  trigger:
    - platform: state
      entity_id: device_tracker.c0eefbd3c35f
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.c0eefbf28296
      from: 'home'
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.c0eefbd3c35f
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.c0eefbf28296
        state: 'not_home'
  action:
    service: notify.notify
    data:
      message: 'nobody home. activate awayon mode?'
      data:
        keyboard: '/awayon test'
- alias : away mode off when someone comes home
  trigger:
    - platform: state
      entity_id: device_tracker.c0eefbd3c35f
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.c0eefbf28296
      from: 'not_home'
      to: 'home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.away
      
#######################################################
# Shades
#######################################################
- alias: activate blind at sunrise but after 8AM
  trigger:
    - platform: sun
      event: sunrise
    - platform: time
      after: '8:01:00'
  condition:
    condition: time
    after: '8:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.64040
- alias: put the shade in privacy mode at a certain time
  trigger:
    - platform: time
      after: '20:00:00'
    - platform: sun
      event: sunset
      offset: '-1:00:00'
  condition:
    condition: sun
    before: sunset
    before_offset: '1:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.7247
- alias: Put the shade in night mode when completely dark
  trigger:
    - platform: sun
      event: sunset
      offset: '1:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.60133
#######################################################
# Away modes
#######################################################
- alias: lights on at timeschedule
  trigger:
    - platform: sun
      event: sunset
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away
        state: 'on'
      - condition: time
        before: '21:00:00'
  action:
    - service: scene.turn_on
      entity_id:
        - scene.table_on
- alias: all lights off at timeschedule
  trigger:
    - platform: time
      after: '22:15'
  condition:
    condition: state
    entity_id: input_boolean.away
    state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.all_off
    - service: script.turn_on
      entity_id: 
        - script.bar_on

#######################################################
# bot events
#######################################################
- alias: bot away mode on command
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/awayon'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.away
- alias: bot away mode off command
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/awayoff'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.away
