# - alias: Set night light when triggered on
#   trigger:
#     platform: state
#     entity_id: light.nachtlamp_bo
#     from: 'off'
#     to: 'on'
#   action:
#     service: scene.turn_on
#     entity_id: scene.nachtlamp_bo

# - alias: Nightlight switch on
#   trigger:
#     platform: time
#     hours: 19
#     minutes: 01
#   action:
#     service: scene.turn_on
#     entity_id: scene.nachtlamp_bo
# - alias: Nightlight switch off
#   trigger:
#     platform: time
#     hours: 7
#     minutes: 30
#   action:
#     service: light.turn_off
#     entity_id: light.nachtlamp_bo
# - alias: scene controller actions
#   trigger:
#     platform: state
#     entity_id: sensor.scene_controller_1_10
#   action:
#     service: scene.turn_on
#     data_template:
#       entity_id: >
#         {% if trigger == 3 %}
#           all_off
#         # {% elif is_state(trigger,'2') %}
#         #   scene.table_full_on
#         # {% elif is_state(trigger,'1') %}
#         #   scene.living_on
#         {% endif %}
  