default_view:
  view: yes
  entities:
    - group.house
    - group.livingshades
    - group.living
    - group.dining
    - group.bar
    - group.room_bo
    - sun.sun
    - sensor.light_lux_sensor_2_0
    - device_tracker.c0eefbd3c35f
    - device_tracker.c0eefbf28296
    - group.batteries
    - climate.huiskamer
    # - media_player.pantercast
batteries:
  name: Batteries
  control: hidden
  entities:
    - sensor.main_button
    - sensor.light_sensor
house:
  name: House
  control: hidden
  entities:
    - script.all_off
    - input_boolean.away
livingshades:
  name: Living room shade
  entities:
    - scene.34037
    - scene.53808
    - scene.64040
    - scene.49867
living:
  name: Living
  control: hidden
  entities:
    - script.living_default_on
    - light.hue_lamp_2
    - light.hue_lamp_3
    - light.hoeklamp
    - light.tv_lamp
    - light.wandlamp1
    - light.wandlamp2
dining:
  name: Dining
  control: hidden
  entities:
    - light.eettafel_1
    - light.eettafel_2
    - scene.table_on
    - scene.table_full_on
bar:
  name: The bar
  entities:
    - light.barlamp
room_bo:
  name: Room Bo
  entities:
    - light.lamp_bo
