- name: table on
  entities:
    light.eettafel_1:
      state: on
      xy_color: [0.5134,0.4149]
      brightness: 150
    light.eettafel_2:
      state: on
      xy_color: [0.5134,0.4149]
      brightness: 150
- name: table full on
  entities:
    light.eettafel_1:
      state: on
      xy_color: [0.5134,0.4149]
      brightness: 254
    light.eettafel_2:
      state: on
      xy_color: [0.5134,0.4149]
      brightness: 254
